2024-04-27 16:55:57,029 INFO Mapper 0 started with PID 11128
2024-04-27 16:55:57,065 INFO Mapper 1 started with PID 27588
2024-04-27 16:55:57,108 INFO Mapper 2 started with PID 27644
2024-04-27 16:55:57,157 INFO Mapper 3 started with PID 8408
2024-04-27 16:55:57,230 INFO Reducer 0 started with PID 2832
2024-04-27 16:55:57,314 INFO Reducer 1 started with PID 29744
2024-04-27 16:55:57,461 INFO Initial random centroids: Centroid 1: (0.8106537569050687, -2.9607554246996735), Centroid 2: (-9.615722957464303, 1.8214400218876108)
2024-04-27 16:55:57,461 INFO Iteration 1 begins
2024-04-27 16:55:57,463 INFO Shard map created: {1: ('points.txt', 0, 6), 2: ('points.txt', 6, 12), 3: ('points.txt', 12, 18), 4: ('points.txt', 18, 25)}
2024-04-27 16:55:57,463 INFO Starting map phase...
2024-04-27 16:55:57,511 INFO Master sends to mapper 1
2024-04-27 16:55:57,542 INFO Master sends to mapper 2
2024-04-27 16:55:57,545 INFO Master sends to mapper 3
2024-04-27 16:55:57,561 INFO Master sends to mapper 4
2024-04-27 16:55:59,886 INFO Mapper 3 generated an exception: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:6003: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-04-27T11:25:59.8782635+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:6003: Connection refused"}"
>
2024-04-27 16:55:59,888 INFO Mapper 1 generated an exception: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:6001: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:6001: Connection refused", grpc_status:14, created_time:"2024-04-27T11:25:59.8826039+00:00"}"
>
2024-04-27 16:55:59,890 INFO Mapper 2 generated an exception: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:6002: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:6002: Connection refused", grpc_status:14, created_time:"2024-04-27T11:25:59.8885181+00:00"}"
>
2024-04-27 16:55:59,927 INFO Mapper 4 generated an exception: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:6004: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:6004: Connection refused", grpc_status:14, created_time:"2024-04-27T11:25:59.9253007+00:00"}"
>
2024-04-27 16:55:59,928 INFO Starting reduce phase...
2024-04-27 16:55:59,943 INFO Reducer 0 failed to start reduce phase
2024-04-27 16:56:02,259 INFO Reducer 0 generated an exception: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:7000: Connection refused"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-04-27T11:26:02.2588965+00:00", grpc_status:14, grpc_message:"failed to connect to all addresses; last error: UNAVAILABLE: ipv4:127.0.0.1:7000: Connection refused"}"
>
2024-04-27 16:56:08,360 INFO Reducer 1 started reduce phase: Reduction completed
2024-04-27 16:56:08,361 INFO New centroids: Centroid 1: (0.8106537569050687, -2.9607554246996735), Centroid 2: (-9.615722957464303, 1.8214400218876108)
2024-04-27 16:56:08,361 INFO Convergence reached.
